// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AlembicVersion      string
	OrganizationMembers string
	Organizations       string
	Projects            string
	Sboms               string
	ScanJobs            string
	Users               string
	Vulnerabilities     string
}{
	AlembicVersion:      "alembic_version",
	OrganizationMembers: "organization_members",
	Organizations:       "organizations",
	Projects:            "projects",
	Sboms:               "sboms",
	ScanJobs:            "scan_jobs",
	Users:               "users",
	Vulnerabilities:     "vulnerabilities",
}
