// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Sbom is an object representing the database table.
type Sbom struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ProjectID    null.Int    `boil:"project_id" json:"project_id,omitempty" toml:"project_id" yaml:"project_id,omitempty"`
	ProjectName  string      `boil:"project_name" json:"project_name" toml:"project_name" yaml:"project_name"`
	ManifestName null.String `boil:"manifest_name" json:"manifest_name,omitempty" toml:"manifest_name" yaml:"manifest_name,omitempty"`
	Source       string      `boil:"source" json:"source" toml:"source" yaml:"source"`
	Sbom         types.JSON  `boil:"sbom" json:"sbom" toml:"sbom" yaml:"sbom"`
	Summary      null.JSON   `boil:"summary" json:"summary,omitempty" toml:"summary" yaml:"summary,omitempty"`
	ObjectURL    null.String `boil:"object_url" json:"object_url,omitempty" toml:"object_url" yaml:"object_url,omitempty"`
	CreatedAt    null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *sbomR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sbomL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SbomColumns = struct {
	ID           string
	ProjectID    string
	ProjectName  string
	ManifestName string
	Source       string
	Sbom         string
	Summary      string
	ObjectURL    string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	ProjectID:    "project_id",
	ProjectName:  "project_name",
	ManifestName: "manifest_name",
	Source:       "source",
	Sbom:         "sbom",
	Summary:      "summary",
	ObjectURL:    "object_url",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var SbomTableColumns = struct {
	ID           string
	ProjectID    string
	ProjectName  string
	ManifestName string
	Source       string
	Sbom         string
	Summary      string
	ObjectURL    string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "sboms.id",
	ProjectID:    "sboms.project_id",
	ProjectName:  "sboms.project_name",
	ManifestName: "sboms.manifest_name",
	Source:       "sboms.source",
	Sbom:         "sboms.sbom",
	Summary:      "sboms.summary",
	ObjectURL:    "sboms.object_url",
	CreatedAt:    "sboms.created_at",
	UpdatedAt:    "sboms.updated_at",
}

// Generated where

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var SbomWhere = struct {
	ID           whereHelperstring
	ProjectID    whereHelpernull_Int
	ProjectName  whereHelperstring
	ManifestName whereHelpernull_String
	Source       whereHelperstring
	Sbom         whereHelpertypes_JSON
	Summary      whereHelpernull_JSON
	ObjectURL    whereHelpernull_String
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"sboms\".\"id\""},
	ProjectID:    whereHelpernull_Int{field: "\"sboms\".\"project_id\""},
	ProjectName:  whereHelperstring{field: "\"sboms\".\"project_name\""},
	ManifestName: whereHelpernull_String{field: "\"sboms\".\"manifest_name\""},
	Source:       whereHelperstring{field: "\"sboms\".\"source\""},
	Sbom:         whereHelpertypes_JSON{field: "\"sboms\".\"sbom\""},
	Summary:      whereHelpernull_JSON{field: "\"sboms\".\"summary\""},
	ObjectURL:    whereHelpernull_String{field: "\"sboms\".\"object_url\""},
	CreatedAt:    whereHelpernull_Time{field: "\"sboms\".\"created_at\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"sboms\".\"updated_at\""},
}

// SbomRels is where relationship names are stored.
var SbomRels = struct {
	Project  string
	ScanJobs string
}{
	Project:  "Project",
	ScanJobs: "ScanJobs",
}

// sbomR is where relationships are stored.
type sbomR struct {
	Project  *Project     `boil:"Project" json:"Project" toml:"Project" yaml:"Project"`
	ScanJobs ScanJobSlice `boil:"ScanJobs" json:"ScanJobs" toml:"ScanJobs" yaml:"ScanJobs"`
}

// NewStruct creates a new relationship struct
func (*sbomR) NewStruct() *sbomR {
	return &sbomR{}
}

func (o *Sbom) GetProject() *Project {
	if o == nil {
		return nil
	}

	return o.R.GetProject()
}

func (r *sbomR) GetProject() *Project {
	if r == nil {
		return nil
	}

	return r.Project
}

func (o *Sbom) GetScanJobs() ScanJobSlice {
	if o == nil {
		return nil
	}

	return o.R.GetScanJobs()
}

func (r *sbomR) GetScanJobs() ScanJobSlice {
	if r == nil {
		return nil
	}

	return r.ScanJobs
}

// sbomL is where Load methods for each relationship are stored.
type sbomL struct{}

var (
	sbomAllColumns            = []string{"id", "project_id", "project_name", "manifest_name", "source", "sbom", "summary", "object_url", "created_at", "updated_at"}
	sbomColumnsWithoutDefault = []string{"project_name", "source", "sbom"}
	sbomColumnsWithDefault    = []string{"id", "project_id", "manifest_name", "summary", "object_url", "created_at", "updated_at"}
	sbomPrimaryKeyColumns     = []string{"id"}
	sbomGeneratedColumns      = []string{}
)

type (
	// SbomSlice is an alias for a slice of pointers to Sbom.
	// This should almost always be used instead of []Sbom.
	SbomSlice []*Sbom
	// SbomHook is the signature for custom Sbom hook methods
	SbomHook func(context.Context, boil.ContextExecutor, *Sbom) error

	sbomQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sbomType                 = reflect.TypeOf(&Sbom{})
	sbomMapping              = queries.MakeStructMapping(sbomType)
	sbomPrimaryKeyMapping, _ = queries.BindMapping(sbomType, sbomMapping, sbomPrimaryKeyColumns)
	sbomInsertCacheMut       sync.RWMutex
	sbomInsertCache          = make(map[string]insertCache)
	sbomUpdateCacheMut       sync.RWMutex
	sbomUpdateCache          = make(map[string]updateCache)
	sbomUpsertCacheMut       sync.RWMutex
	sbomUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var sbomAfterSelectMu sync.Mutex
var sbomAfterSelectHooks []SbomHook

var sbomBeforeInsertMu sync.Mutex
var sbomBeforeInsertHooks []SbomHook
var sbomAfterInsertMu sync.Mutex
var sbomAfterInsertHooks []SbomHook

var sbomBeforeUpdateMu sync.Mutex
var sbomBeforeUpdateHooks []SbomHook
var sbomAfterUpdateMu sync.Mutex
var sbomAfterUpdateHooks []SbomHook

var sbomBeforeDeleteMu sync.Mutex
var sbomBeforeDeleteHooks []SbomHook
var sbomAfterDeleteMu sync.Mutex
var sbomAfterDeleteHooks []SbomHook

var sbomBeforeUpsertMu sync.Mutex
var sbomBeforeUpsertHooks []SbomHook
var sbomAfterUpsertMu sync.Mutex
var sbomAfterUpsertHooks []SbomHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Sbom) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Sbom) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Sbom) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Sbom) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Sbom) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Sbom) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Sbom) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Sbom) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Sbom) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sbomAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSbomHook registers your hook function for all future operations.
func AddSbomHook(hookPoint boil.HookPoint, sbomHook SbomHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		sbomAfterSelectMu.Lock()
		sbomAfterSelectHooks = append(sbomAfterSelectHooks, sbomHook)
		sbomAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		sbomBeforeInsertMu.Lock()
		sbomBeforeInsertHooks = append(sbomBeforeInsertHooks, sbomHook)
		sbomBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		sbomAfterInsertMu.Lock()
		sbomAfterInsertHooks = append(sbomAfterInsertHooks, sbomHook)
		sbomAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		sbomBeforeUpdateMu.Lock()
		sbomBeforeUpdateHooks = append(sbomBeforeUpdateHooks, sbomHook)
		sbomBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		sbomAfterUpdateMu.Lock()
		sbomAfterUpdateHooks = append(sbomAfterUpdateHooks, sbomHook)
		sbomAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		sbomBeforeDeleteMu.Lock()
		sbomBeforeDeleteHooks = append(sbomBeforeDeleteHooks, sbomHook)
		sbomBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		sbomAfterDeleteMu.Lock()
		sbomAfterDeleteHooks = append(sbomAfterDeleteHooks, sbomHook)
		sbomAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		sbomBeforeUpsertMu.Lock()
		sbomBeforeUpsertHooks = append(sbomBeforeUpsertHooks, sbomHook)
		sbomBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		sbomAfterUpsertMu.Lock()
		sbomAfterUpsertHooks = append(sbomAfterUpsertHooks, sbomHook)
		sbomAfterUpsertMu.Unlock()
	}
}

// One returns a single sbom record from the query.
func (q sbomQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Sbom, error) {
	o := &Sbom{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for sboms")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Sbom records from the query.
func (q sbomQuery) All(ctx context.Context, exec boil.ContextExecutor) (SbomSlice, error) {
	var o []*Sbom

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Sbom slice")
	}

	if len(sbomAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Sbom records in the query.
func (q sbomQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count sboms rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q sbomQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if sboms exists")
	}

	return count > 0, nil
}

// Project pointed to by the foreign key.
func (o *Sbom) Project(mods ...qm.QueryMod) projectQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProjectID),
	}

	queryMods = append(queryMods, mods...)

	return Projects(queryMods...)
}

// ScanJobs retrieves all the scan_job's ScanJobs with an executor.
func (o *Sbom) ScanJobs(mods ...qm.QueryMod) scanJobQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"scan_jobs\".\"sbom_id\"=?", o.ID),
	)

	return ScanJobs(queryMods...)
}

// LoadProject allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (sbomL) LoadProject(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSbom interface{}, mods queries.Applicator) error {
	var slice []*Sbom
	var object *Sbom

	if singular {
		var ok bool
		object, ok = maybeSbom.(*Sbom)
		if !ok {
			object = new(Sbom)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSbom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSbom))
			}
		}
	} else {
		s, ok := maybeSbom.(*[]*Sbom)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSbom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSbom))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &sbomR{}
		}
		if !queries.IsNil(object.ProjectID) {
			args[object.ProjectID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sbomR{}
			}

			if !queries.IsNil(obj.ProjectID) {
				args[obj.ProjectID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`projects`),
		qm.WhereIn(`projects.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Project")
	}

	var resultSlice []*Project
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Project")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for projects")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for projects")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Project = foreign
		if foreign.R == nil {
			foreign.R = &projectR{}
		}
		foreign.R.Sboms = append(foreign.R.Sboms, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ProjectID, foreign.ID) {
				local.R.Project = foreign
				if foreign.R == nil {
					foreign.R = &projectR{}
				}
				foreign.R.Sboms = append(foreign.R.Sboms, local)
				break
			}
		}
	}

	return nil
}

// LoadScanJobs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (sbomL) LoadScanJobs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSbom interface{}, mods queries.Applicator) error {
	var slice []*Sbom
	var object *Sbom

	if singular {
		var ok bool
		object, ok = maybeSbom.(*Sbom)
		if !ok {
			object = new(Sbom)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSbom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSbom))
			}
		}
	} else {
		s, ok := maybeSbom.(*[]*Sbom)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSbom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSbom))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &sbomR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sbomR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`scan_jobs`),
		qm.WhereIn(`scan_jobs.sbom_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load scan_jobs")
	}

	var resultSlice []*ScanJob
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice scan_jobs")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on scan_jobs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for scan_jobs")
	}

	if len(scanJobAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ScanJobs = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &scanJobR{}
			}
			foreign.R.Sbom = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.SbomID) {
				local.R.ScanJobs = append(local.R.ScanJobs, foreign)
				if foreign.R == nil {
					foreign.R = &scanJobR{}
				}
				foreign.R.Sbom = local
				break
			}
		}
	}

	return nil
}

// SetProject of the sbom to the related item.
// Sets o.R.Project to related.
// Adds o to related.R.Sboms.
func (o *Sbom) SetProject(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Project) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"sboms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"project_id"}),
		strmangle.WhereClause("\"", "\"", 2, sbomPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ProjectID, related.ID)
	if o.R == nil {
		o.R = &sbomR{
			Project: related,
		}
	} else {
		o.R.Project = related
	}

	if related.R == nil {
		related.R = &projectR{
			Sboms: SbomSlice{o},
		}
	} else {
		related.R.Sboms = append(related.R.Sboms, o)
	}

	return nil
}

// RemoveProject relationship.
// Sets o.R.Project to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Sbom) RemoveProject(ctx context.Context, exec boil.ContextExecutor, related *Project) error {
	var err error

	queries.SetScanner(&o.ProjectID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("project_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Project = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Sboms {
		if queries.Equal(o.ProjectID, ri.ProjectID) {
			continue
		}

		ln := len(related.R.Sboms)
		if ln > 1 && i < ln-1 {
			related.R.Sboms[i] = related.R.Sboms[ln-1]
		}
		related.R.Sboms = related.R.Sboms[:ln-1]
		break
	}
	return nil
}

// AddScanJobs adds the given related objects to the existing relationships
// of the sbom, optionally inserting them as new records.
// Appends related to o.R.ScanJobs.
// Sets related.R.Sbom appropriately.
func (o *Sbom) AddScanJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ScanJob) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.SbomID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"scan_jobs\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"sbom_id"}),
				strmangle.WhereClause("\"", "\"", 2, scanJobPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.SbomID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &sbomR{
			ScanJobs: related,
		}
	} else {
		o.R.ScanJobs = append(o.R.ScanJobs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &scanJobR{
				Sbom: o,
			}
		} else {
			rel.R.Sbom = o
		}
	}
	return nil
}

// SetScanJobs removes all previously related items of the
// sbom replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Sbom's ScanJobs accordingly.
// Replaces o.R.ScanJobs with related.
// Sets related.R.Sbom's ScanJobs accordingly.
func (o *Sbom) SetScanJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ScanJob) error {
	query := "update \"scan_jobs\" set \"sbom_id\" = null where \"sbom_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ScanJobs {
			queries.SetScanner(&rel.SbomID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Sbom = nil
		}
		o.R.ScanJobs = nil
	}

	return o.AddScanJobs(ctx, exec, insert, related...)
}

// RemoveScanJobs relationships from objects passed in.
// Removes related items from R.ScanJobs (uses pointer comparison, removal does not keep order)
// Sets related.R.Sbom.
func (o *Sbom) RemoveScanJobs(ctx context.Context, exec boil.ContextExecutor, related ...*ScanJob) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.SbomID, nil)
		if rel.R != nil {
			rel.R.Sbom = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("sbom_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ScanJobs {
			if rel != ri {
				continue
			}

			ln := len(o.R.ScanJobs)
			if ln > 1 && i < ln-1 {
				o.R.ScanJobs[i] = o.R.ScanJobs[ln-1]
			}
			o.R.ScanJobs = o.R.ScanJobs[:ln-1]
			break
		}
	}

	return nil
}

// Sboms retrieves all the records using an executor.
func Sboms(mods ...qm.QueryMod) sbomQuery {
	mods = append(mods, qm.From("\"sboms\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"sboms\".*"})
	}

	return sbomQuery{q}
}

// FindSbom retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSbom(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Sbom, error) {
	sbomObj := &Sbom{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"sboms\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, sbomObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from sboms")
	}

	if err = sbomObj.doAfterSelectHooks(ctx, exec); err != nil {
		return sbomObj, err
	}

	return sbomObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Sbom) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sboms provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sbomColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sbomInsertCacheMut.RLock()
	cache, cached := sbomInsertCache[key]
	sbomInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sbomAllColumns,
			sbomColumnsWithDefault,
			sbomColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(sbomType, sbomMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sbomType, sbomMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"sboms\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"sboms\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into sboms")
	}

	if !cached {
		sbomInsertCacheMut.Lock()
		sbomInsertCache[key] = cache
		sbomInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Sbom.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Sbom) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	sbomUpdateCacheMut.RLock()
	cache, cached := sbomUpdateCache[key]
	sbomUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sbomAllColumns,
			sbomPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update sboms, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"sboms\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, sbomPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sbomType, sbomMapping, append(wl, sbomPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update sboms row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for sboms")
	}

	if !cached {
		sbomUpdateCacheMut.Lock()
		sbomUpdateCache[key] = cache
		sbomUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q sbomQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for sboms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for sboms")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SbomSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sbomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"sboms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, sbomPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in sbom slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all sbom")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Sbom) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no sboms provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sbomColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sbomUpsertCacheMut.RLock()
	cache, cached := sbomUpsertCache[key]
	sbomUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			sbomAllColumns,
			sbomColumnsWithDefault,
			sbomColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			sbomAllColumns,
			sbomPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert sboms, could not build update column list")
		}

		ret := strmangle.SetComplement(sbomAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(sbomPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert sboms, could not build conflict column list")
			}

			conflict = make([]string, len(sbomPrimaryKeyColumns))
			copy(conflict, sbomPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"sboms\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(sbomType, sbomMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sbomType, sbomMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert sboms")
	}

	if !cached {
		sbomUpsertCacheMut.Lock()
		sbomUpsertCache[key] = cache
		sbomUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Sbom record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Sbom) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Sbom provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sbomPrimaryKeyMapping)
	sql := "DELETE FROM \"sboms\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from sboms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for sboms")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q sbomQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no sbomQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sboms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sboms")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SbomSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(sbomBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sbomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"sboms\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, sbomPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sbom slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sboms")
	}

	if len(sbomAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Sbom) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSbom(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SbomSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SbomSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sbomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"sboms\".* FROM \"sboms\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, sbomPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SbomSlice")
	}

	*o = slice

	return nil
}

// SbomExists checks if the Sbom row exists.
func SbomExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"sboms\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if sboms exists")
	}

	return exists, nil
}

// Exists checks if the Sbom row exists.
func (o *Sbom) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SbomExists(ctx, exec, o.ID)
}
