// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSboms(t *testing.T) {
	t.Parallel()

	query := Sboms()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSbomsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSbomsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Sboms().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSbomsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SbomSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSbomsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SbomExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Sbom exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SbomExists to return true, but got false.")
	}
}

func testSbomsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	sbomFound, err := FindSbom(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if sbomFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSbomsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Sboms().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSbomsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Sboms().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSbomsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	sbomOne := &Sbom{}
	sbomTwo := &Sbom{}
	if err = randomize.Struct(seed, sbomOne, sbomDBTypes, false, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}
	if err = randomize.Struct(seed, sbomTwo, sbomDBTypes, false, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sbomOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sbomTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Sboms().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSbomsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	sbomOne := &Sbom{}
	sbomTwo := &Sbom{}
	if err = randomize.Struct(seed, sbomOne, sbomDBTypes, false, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}
	if err = randomize.Struct(seed, sbomTwo, sbomDBTypes, false, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sbomOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sbomTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func sbomBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func sbomAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func sbomAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func sbomBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func sbomAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func sbomBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func sbomAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func sbomBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func sbomAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
	*o = Sbom{}
	return nil
}

func testSbomsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Sbom{}
	o := &Sbom{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, sbomDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Sbom object: %s", err)
	}

	AddSbomHook(boil.BeforeInsertHook, sbomBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	sbomBeforeInsertHooks = []SbomHook{}

	AddSbomHook(boil.AfterInsertHook, sbomAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	sbomAfterInsertHooks = []SbomHook{}

	AddSbomHook(boil.AfterSelectHook, sbomAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	sbomAfterSelectHooks = []SbomHook{}

	AddSbomHook(boil.BeforeUpdateHook, sbomBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	sbomBeforeUpdateHooks = []SbomHook{}

	AddSbomHook(boil.AfterUpdateHook, sbomAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	sbomAfterUpdateHooks = []SbomHook{}

	AddSbomHook(boil.BeforeDeleteHook, sbomBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	sbomBeforeDeleteHooks = []SbomHook{}

	AddSbomHook(boil.AfterDeleteHook, sbomAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	sbomAfterDeleteHooks = []SbomHook{}

	AddSbomHook(boil.BeforeUpsertHook, sbomBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	sbomBeforeUpsertHooks = []SbomHook{}

	AddSbomHook(boil.AfterUpsertHook, sbomAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	sbomAfterUpsertHooks = []SbomHook{}
}

func testSbomsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSbomsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSbomToManyScanJobs(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Sbom
	var b, c ScanJob

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, scanJobDBTypes, false, scanJobColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, scanJobDBTypes, false, scanJobColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.SbomID, a.ID)
	queries.Assign(&c.SbomID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.ScanJobs().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.SbomID, b.SbomID) {
			bFound = true
		}
		if queries.Equal(v.SbomID, c.SbomID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SbomSlice{&a}
	if err = a.L.LoadScanJobs(ctx, tx, false, (*[]*Sbom)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ScanJobs); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.ScanJobs = nil
	if err = a.L.LoadScanJobs(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ScanJobs); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSbomToManyAddOpScanJobs(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Sbom
	var b, c, d, e ScanJob

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sbomDBTypes, false, strmangle.SetComplement(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ScanJob{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*ScanJob{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddScanJobs(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.SbomID) {
			t.Error("foreign key was wrong value", a.ID, first.SbomID)
		}
		if !queries.Equal(a.ID, second.SbomID) {
			t.Error("foreign key was wrong value", a.ID, second.SbomID)
		}

		if first.R.Sbom != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Sbom != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.ScanJobs[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.ScanJobs[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.ScanJobs().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSbomToManySetOpScanJobs(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Sbom
	var b, c, d, e ScanJob

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sbomDBTypes, false, strmangle.SetComplement(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ScanJob{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetScanJobs(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetScanJobs(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SbomID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SbomID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.SbomID) {
		t.Error("foreign key was wrong value", a.ID, d.SbomID)
	}
	if !queries.Equal(a.ID, e.SbomID) {
		t.Error("foreign key was wrong value", a.ID, e.SbomID)
	}

	if b.R.Sbom != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Sbom != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Sbom != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Sbom != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.ScanJobs[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.ScanJobs[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testSbomToManyRemoveOpScanJobs(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Sbom
	var b, c, d, e ScanJob

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sbomDBTypes, false, strmangle.SetComplement(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ScanJob{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddScanJobs(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveScanJobs(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SbomID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SbomID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Sbom != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Sbom != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Sbom != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Sbom != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.ScanJobs) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.ScanJobs[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.ScanJobs[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testSbomToOneProjectUsingProject(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Sbom
	var foreign Project

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, projectDBTypes, false, projectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Project struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.ProjectID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Project().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddProjectHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Project) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SbomSlice{&local}
	if err = local.L.LoadProject(ctx, tx, false, (*[]*Sbom)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Project == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Project = nil
	if err = local.L.LoadProject(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Project == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSbomToOneSetOpProjectUsingProject(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Sbom
	var b, c Project

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sbomDBTypes, false, strmangle.SetComplement(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, projectDBTypes, false, strmangle.SetComplement(projectPrimaryKeyColumns, projectColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, projectDBTypes, false, strmangle.SetComplement(projectPrimaryKeyColumns, projectColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Project{&b, &c} {
		err = a.SetProject(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Project != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Sboms[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.ProjectID, x.ID) {
			t.Error("foreign key was wrong value", a.ProjectID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ProjectID))
		reflect.Indirect(reflect.ValueOf(&a.ProjectID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.ProjectID, x.ID) {
			t.Error("foreign key was wrong value", a.ProjectID, x.ID)
		}
	}
}

func testSbomToOneRemoveOpProjectUsingProject(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Sbom
	var b Project

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sbomDBTypes, false, strmangle.SetComplement(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, projectDBTypes, false, strmangle.SetComplement(projectPrimaryKeyColumns, projectColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetProject(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveProject(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Project().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Project != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.ProjectID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Sboms) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testSbomsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSbomsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SbomSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSbomsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Sboms().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	sbomDBTypes = map[string]string{`ID`: `uuid`, `ProjectID`: `integer`, `ProjectName`: `character varying`, `ManifestName`: `text`, `Source`: `character varying`, `Sbom`: `jsonb`, `Summary`: `jsonb`, `ObjectURL`: `character varying`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_           = bytes.MinRead
)

func testSbomsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(sbomPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(sbomAllColumns) == len(sbomPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSbomsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(sbomAllColumns) == len(sbomPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Sbom{}
	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sbomDBTypes, true, sbomPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(sbomAllColumns, sbomPrimaryKeyColumns) {
		fields = sbomAllColumns
	} else {
		fields = strmangle.SetComplement(
			sbomAllColumns,
			sbomPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SbomSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSbomsUpsert(t *testing.T) {
	t.Parallel()

	if len(sbomAllColumns) == len(sbomPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Sbom{}
	if err = randomize.Struct(seed, &o, sbomDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Sbom: %s", err)
	}

	count, err := Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, sbomDBTypes, false, sbomPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Sbom: %s", err)
	}

	count, err = Sboms().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
