// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ScanJob is an object representing the database table.
type ScanJob struct {
	ID          int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	ProjectID   null.Int    `boil:"project_id" json:"project_id,omitempty" toml:"project_id" yaml:"project_id,omitempty"`
	SbomID      null.String `boil:"sbom_id" json:"sbom_id,omitempty" toml:"sbom_id" yaml:"sbom_id,omitempty"`
	Status      null.String `boil:"status" json:"status,omitempty" toml:"status" yaml:"status,omitempty"`
	ScanType    null.String `boil:"scan_type" json:"scan_type,omitempty" toml:"scan_type" yaml:"scan_type,omitempty"`
	TriggeredBy null.Int    `boil:"triggered_by" json:"triggered_by,omitempty" toml:"triggered_by" yaml:"triggered_by,omitempty"`
	StartedAt   null.Time   `boil:"started_at" json:"started_at,omitempty" toml:"started_at" yaml:"started_at,omitempty"`
	FinishedAt  null.Time   `boil:"finished_at" json:"finished_at,omitempty" toml:"finished_at" yaml:"finished_at,omitempty"`
	ErrorLog    null.String `boil:"error_log" json:"error_log,omitempty" toml:"error_log" yaml:"error_log,omitempty"`
	Meta        null.JSON   `boil:"meta" json:"meta,omitempty" toml:"meta" yaml:"meta,omitempty"`
	CreatedAt   null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`

	R *scanJobR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L scanJobL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ScanJobColumns = struct {
	ID          string
	ProjectID   string
	SbomID      string
	Status      string
	ScanType    string
	TriggeredBy string
	StartedAt   string
	FinishedAt  string
	ErrorLog    string
	Meta        string
	CreatedAt   string
}{
	ID:          "id",
	ProjectID:   "project_id",
	SbomID:      "sbom_id",
	Status:      "status",
	ScanType:    "scan_type",
	TriggeredBy: "triggered_by",
	StartedAt:   "started_at",
	FinishedAt:  "finished_at",
	ErrorLog:    "error_log",
	Meta:        "meta",
	CreatedAt:   "created_at",
}

var ScanJobTableColumns = struct {
	ID          string
	ProjectID   string
	SbomID      string
	Status      string
	ScanType    string
	TriggeredBy string
	StartedAt   string
	FinishedAt  string
	ErrorLog    string
	Meta        string
	CreatedAt   string
}{
	ID:          "scan_jobs.id",
	ProjectID:   "scan_jobs.project_id",
	SbomID:      "scan_jobs.sbom_id",
	Status:      "scan_jobs.status",
	ScanType:    "scan_jobs.scan_type",
	TriggeredBy: "scan_jobs.triggered_by",
	StartedAt:   "scan_jobs.started_at",
	FinishedAt:  "scan_jobs.finished_at",
	ErrorLog:    "scan_jobs.error_log",
	Meta:        "scan_jobs.meta",
	CreatedAt:   "scan_jobs.created_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ScanJobWhere = struct {
	ID          whereHelperint64
	ProjectID   whereHelpernull_Int
	SbomID      whereHelpernull_String
	Status      whereHelpernull_String
	ScanType    whereHelpernull_String
	TriggeredBy whereHelpernull_Int
	StartedAt   whereHelpernull_Time
	FinishedAt  whereHelpernull_Time
	ErrorLog    whereHelpernull_String
	Meta        whereHelpernull_JSON
	CreatedAt   whereHelpernull_Time
}{
	ID:          whereHelperint64{field: "\"scan_jobs\".\"id\""},
	ProjectID:   whereHelpernull_Int{field: "\"scan_jobs\".\"project_id\""},
	SbomID:      whereHelpernull_String{field: "\"scan_jobs\".\"sbom_id\""},
	Status:      whereHelpernull_String{field: "\"scan_jobs\".\"status\""},
	ScanType:    whereHelpernull_String{field: "\"scan_jobs\".\"scan_type\""},
	TriggeredBy: whereHelpernull_Int{field: "\"scan_jobs\".\"triggered_by\""},
	StartedAt:   whereHelpernull_Time{field: "\"scan_jobs\".\"started_at\""},
	FinishedAt:  whereHelpernull_Time{field: "\"scan_jobs\".\"finished_at\""},
	ErrorLog:    whereHelpernull_String{field: "\"scan_jobs\".\"error_log\""},
	Meta:        whereHelpernull_JSON{field: "\"scan_jobs\".\"meta\""},
	CreatedAt:   whereHelpernull_Time{field: "\"scan_jobs\".\"created_at\""},
}

// ScanJobRels is where relationship names are stored.
var ScanJobRels = struct {
	Project         string
	Sbom            string
	TriggeredByUser string
}{
	Project:         "Project",
	Sbom:            "Sbom",
	TriggeredByUser: "TriggeredByUser",
}

// scanJobR is where relationships are stored.
type scanJobR struct {
	Project         *Project `boil:"Project" json:"Project" toml:"Project" yaml:"Project"`
	Sbom            *Sbom    `boil:"Sbom" json:"Sbom" toml:"Sbom" yaml:"Sbom"`
	TriggeredByUser *User    `boil:"TriggeredByUser" json:"TriggeredByUser" toml:"TriggeredByUser" yaml:"TriggeredByUser"`
}

// NewStruct creates a new relationship struct
func (*scanJobR) NewStruct() *scanJobR {
	return &scanJobR{}
}

func (o *ScanJob) GetProject() *Project {
	if o == nil {
		return nil
	}

	return o.R.GetProject()
}

func (r *scanJobR) GetProject() *Project {
	if r == nil {
		return nil
	}

	return r.Project
}

func (o *ScanJob) GetSbom() *Sbom {
	if o == nil {
		return nil
	}

	return o.R.GetSbom()
}

func (r *scanJobR) GetSbom() *Sbom {
	if r == nil {
		return nil
	}

	return r.Sbom
}

func (o *ScanJob) GetTriggeredByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetTriggeredByUser()
}

func (r *scanJobR) GetTriggeredByUser() *User {
	if r == nil {
		return nil
	}

	return r.TriggeredByUser
}

// scanJobL is where Load methods for each relationship are stored.
type scanJobL struct{}

var (
	scanJobAllColumns            = []string{"id", "project_id", "sbom_id", "status", "scan_type", "triggered_by", "started_at", "finished_at", "error_log", "meta", "created_at"}
	scanJobColumnsWithoutDefault = []string{}
	scanJobColumnsWithDefault    = []string{"id", "project_id", "sbom_id", "status", "scan_type", "triggered_by", "started_at", "finished_at", "error_log", "meta", "created_at"}
	scanJobPrimaryKeyColumns     = []string{"id"}
	scanJobGeneratedColumns      = []string{}
)

type (
	// ScanJobSlice is an alias for a slice of pointers to ScanJob.
	// This should almost always be used instead of []ScanJob.
	ScanJobSlice []*ScanJob
	// ScanJobHook is the signature for custom ScanJob hook methods
	ScanJobHook func(context.Context, boil.ContextExecutor, *ScanJob) error

	scanJobQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	scanJobType                 = reflect.TypeOf(&ScanJob{})
	scanJobMapping              = queries.MakeStructMapping(scanJobType)
	scanJobPrimaryKeyMapping, _ = queries.BindMapping(scanJobType, scanJobMapping, scanJobPrimaryKeyColumns)
	scanJobInsertCacheMut       sync.RWMutex
	scanJobInsertCache          = make(map[string]insertCache)
	scanJobUpdateCacheMut       sync.RWMutex
	scanJobUpdateCache          = make(map[string]updateCache)
	scanJobUpsertCacheMut       sync.RWMutex
	scanJobUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var scanJobAfterSelectMu sync.Mutex
var scanJobAfterSelectHooks []ScanJobHook

var scanJobBeforeInsertMu sync.Mutex
var scanJobBeforeInsertHooks []ScanJobHook
var scanJobAfterInsertMu sync.Mutex
var scanJobAfterInsertHooks []ScanJobHook

var scanJobBeforeUpdateMu sync.Mutex
var scanJobBeforeUpdateHooks []ScanJobHook
var scanJobAfterUpdateMu sync.Mutex
var scanJobAfterUpdateHooks []ScanJobHook

var scanJobBeforeDeleteMu sync.Mutex
var scanJobBeforeDeleteHooks []ScanJobHook
var scanJobAfterDeleteMu sync.Mutex
var scanJobAfterDeleteHooks []ScanJobHook

var scanJobBeforeUpsertMu sync.Mutex
var scanJobBeforeUpsertHooks []ScanJobHook
var scanJobAfterUpsertMu sync.Mutex
var scanJobAfterUpsertHooks []ScanJobHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ScanJob) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ScanJob) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ScanJob) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ScanJob) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ScanJob) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ScanJob) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ScanJob) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ScanJob) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ScanJob) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scanJobAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddScanJobHook registers your hook function for all future operations.
func AddScanJobHook(hookPoint boil.HookPoint, scanJobHook ScanJobHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		scanJobAfterSelectMu.Lock()
		scanJobAfterSelectHooks = append(scanJobAfterSelectHooks, scanJobHook)
		scanJobAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		scanJobBeforeInsertMu.Lock()
		scanJobBeforeInsertHooks = append(scanJobBeforeInsertHooks, scanJobHook)
		scanJobBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		scanJobAfterInsertMu.Lock()
		scanJobAfterInsertHooks = append(scanJobAfterInsertHooks, scanJobHook)
		scanJobAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		scanJobBeforeUpdateMu.Lock()
		scanJobBeforeUpdateHooks = append(scanJobBeforeUpdateHooks, scanJobHook)
		scanJobBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		scanJobAfterUpdateMu.Lock()
		scanJobAfterUpdateHooks = append(scanJobAfterUpdateHooks, scanJobHook)
		scanJobAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		scanJobBeforeDeleteMu.Lock()
		scanJobBeforeDeleteHooks = append(scanJobBeforeDeleteHooks, scanJobHook)
		scanJobBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		scanJobAfterDeleteMu.Lock()
		scanJobAfterDeleteHooks = append(scanJobAfterDeleteHooks, scanJobHook)
		scanJobAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		scanJobBeforeUpsertMu.Lock()
		scanJobBeforeUpsertHooks = append(scanJobBeforeUpsertHooks, scanJobHook)
		scanJobBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		scanJobAfterUpsertMu.Lock()
		scanJobAfterUpsertHooks = append(scanJobAfterUpsertHooks, scanJobHook)
		scanJobAfterUpsertMu.Unlock()
	}
}

// One returns a single scanJob record from the query.
func (q scanJobQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ScanJob, error) {
	o := &ScanJob{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for scan_jobs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ScanJob records from the query.
func (q scanJobQuery) All(ctx context.Context, exec boil.ContextExecutor) (ScanJobSlice, error) {
	var o []*ScanJob

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ScanJob slice")
	}

	if len(scanJobAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ScanJob records in the query.
func (q scanJobQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count scan_jobs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q scanJobQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if scan_jobs exists")
	}

	return count > 0, nil
}

// Project pointed to by the foreign key.
func (o *ScanJob) Project(mods ...qm.QueryMod) projectQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProjectID),
	}

	queryMods = append(queryMods, mods...)

	return Projects(queryMods...)
}

// Sbom pointed to by the foreign key.
func (o *ScanJob) Sbom(mods ...qm.QueryMod) sbomQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SbomID),
	}

	queryMods = append(queryMods, mods...)

	return Sboms(queryMods...)
}

// TriggeredByUser pointed to by the foreign key.
func (o *ScanJob) TriggeredByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TriggeredBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadProject allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (scanJobL) LoadProject(ctx context.Context, e boil.ContextExecutor, singular bool, maybeScanJob interface{}, mods queries.Applicator) error {
	var slice []*ScanJob
	var object *ScanJob

	if singular {
		var ok bool
		object, ok = maybeScanJob.(*ScanJob)
		if !ok {
			object = new(ScanJob)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeScanJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeScanJob))
			}
		}
	} else {
		s, ok := maybeScanJob.(*[]*ScanJob)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeScanJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeScanJob))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &scanJobR{}
		}
		if !queries.IsNil(object.ProjectID) {
			args[object.ProjectID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &scanJobR{}
			}

			if !queries.IsNil(obj.ProjectID) {
				args[obj.ProjectID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`projects`),
		qm.WhereIn(`projects.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Project")
	}

	var resultSlice []*Project
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Project")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for projects")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for projects")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Project = foreign
		if foreign.R == nil {
			foreign.R = &projectR{}
		}
		foreign.R.ScanJobs = append(foreign.R.ScanJobs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ProjectID, foreign.ID) {
				local.R.Project = foreign
				if foreign.R == nil {
					foreign.R = &projectR{}
				}
				foreign.R.ScanJobs = append(foreign.R.ScanJobs, local)
				break
			}
		}
	}

	return nil
}

// LoadSbom allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (scanJobL) LoadSbom(ctx context.Context, e boil.ContextExecutor, singular bool, maybeScanJob interface{}, mods queries.Applicator) error {
	var slice []*ScanJob
	var object *ScanJob

	if singular {
		var ok bool
		object, ok = maybeScanJob.(*ScanJob)
		if !ok {
			object = new(ScanJob)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeScanJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeScanJob))
			}
		}
	} else {
		s, ok := maybeScanJob.(*[]*ScanJob)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeScanJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeScanJob))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &scanJobR{}
		}
		if !queries.IsNil(object.SbomID) {
			args[object.SbomID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &scanJobR{}
			}

			if !queries.IsNil(obj.SbomID) {
				args[obj.SbomID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`sboms`),
		qm.WhereIn(`sboms.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Sbom")
	}

	var resultSlice []*Sbom
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Sbom")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sboms")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sboms")
	}

	if len(sbomAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Sbom = foreign
		if foreign.R == nil {
			foreign.R = &sbomR{}
		}
		foreign.R.ScanJobs = append(foreign.R.ScanJobs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.SbomID, foreign.ID) {
				local.R.Sbom = foreign
				if foreign.R == nil {
					foreign.R = &sbomR{}
				}
				foreign.R.ScanJobs = append(foreign.R.ScanJobs, local)
				break
			}
		}
	}

	return nil
}

// LoadTriggeredByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (scanJobL) LoadTriggeredByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeScanJob interface{}, mods queries.Applicator) error {
	var slice []*ScanJob
	var object *ScanJob

	if singular {
		var ok bool
		object, ok = maybeScanJob.(*ScanJob)
		if !ok {
			object = new(ScanJob)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeScanJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeScanJob))
			}
		}
	} else {
		s, ok := maybeScanJob.(*[]*ScanJob)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeScanJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeScanJob))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &scanJobR{}
		}
		if !queries.IsNil(object.TriggeredBy) {
			args[object.TriggeredBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &scanJobR{}
			}

			if !queries.IsNil(obj.TriggeredBy) {
				args[obj.TriggeredBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.TriggeredByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.TriggeredByScanJobs = append(foreign.R.TriggeredByScanJobs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.TriggeredBy, foreign.ID) {
				local.R.TriggeredByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.TriggeredByScanJobs = append(foreign.R.TriggeredByScanJobs, local)
				break
			}
		}
	}

	return nil
}

// SetProject of the scanJob to the related item.
// Sets o.R.Project to related.
// Adds o to related.R.ScanJobs.
func (o *ScanJob) SetProject(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Project) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"scan_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"project_id"}),
		strmangle.WhereClause("\"", "\"", 2, scanJobPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ProjectID, related.ID)
	if o.R == nil {
		o.R = &scanJobR{
			Project: related,
		}
	} else {
		o.R.Project = related
	}

	if related.R == nil {
		related.R = &projectR{
			ScanJobs: ScanJobSlice{o},
		}
	} else {
		related.R.ScanJobs = append(related.R.ScanJobs, o)
	}

	return nil
}

// RemoveProject relationship.
// Sets o.R.Project to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ScanJob) RemoveProject(ctx context.Context, exec boil.ContextExecutor, related *Project) error {
	var err error

	queries.SetScanner(&o.ProjectID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("project_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Project = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ScanJobs {
		if queries.Equal(o.ProjectID, ri.ProjectID) {
			continue
		}

		ln := len(related.R.ScanJobs)
		if ln > 1 && i < ln-1 {
			related.R.ScanJobs[i] = related.R.ScanJobs[ln-1]
		}
		related.R.ScanJobs = related.R.ScanJobs[:ln-1]
		break
	}
	return nil
}

// SetSbom of the scanJob to the related item.
// Sets o.R.Sbom to related.
// Adds o to related.R.ScanJobs.
func (o *ScanJob) SetSbom(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Sbom) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"scan_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"sbom_id"}),
		strmangle.WhereClause("\"", "\"", 2, scanJobPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.SbomID, related.ID)
	if o.R == nil {
		o.R = &scanJobR{
			Sbom: related,
		}
	} else {
		o.R.Sbom = related
	}

	if related.R == nil {
		related.R = &sbomR{
			ScanJobs: ScanJobSlice{o},
		}
	} else {
		related.R.ScanJobs = append(related.R.ScanJobs, o)
	}

	return nil
}

// RemoveSbom relationship.
// Sets o.R.Sbom to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ScanJob) RemoveSbom(ctx context.Context, exec boil.ContextExecutor, related *Sbom) error {
	var err error

	queries.SetScanner(&o.SbomID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("sbom_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Sbom = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ScanJobs {
		if queries.Equal(o.SbomID, ri.SbomID) {
			continue
		}

		ln := len(related.R.ScanJobs)
		if ln > 1 && i < ln-1 {
			related.R.ScanJobs[i] = related.R.ScanJobs[ln-1]
		}
		related.R.ScanJobs = related.R.ScanJobs[:ln-1]
		break
	}
	return nil
}

// SetTriggeredByUser of the scanJob to the related item.
// Sets o.R.TriggeredByUser to related.
// Adds o to related.R.TriggeredByScanJobs.
func (o *ScanJob) SetTriggeredByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"scan_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"triggered_by"}),
		strmangle.WhereClause("\"", "\"", 2, scanJobPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.TriggeredBy, related.ID)
	if o.R == nil {
		o.R = &scanJobR{
			TriggeredByUser: related,
		}
	} else {
		o.R.TriggeredByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			TriggeredByScanJobs: ScanJobSlice{o},
		}
	} else {
		related.R.TriggeredByScanJobs = append(related.R.TriggeredByScanJobs, o)
	}

	return nil
}

// RemoveTriggeredByUser relationship.
// Sets o.R.TriggeredByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ScanJob) RemoveTriggeredByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.TriggeredBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("triggered_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.TriggeredByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.TriggeredByScanJobs {
		if queries.Equal(o.TriggeredBy, ri.TriggeredBy) {
			continue
		}

		ln := len(related.R.TriggeredByScanJobs)
		if ln > 1 && i < ln-1 {
			related.R.TriggeredByScanJobs[i] = related.R.TriggeredByScanJobs[ln-1]
		}
		related.R.TriggeredByScanJobs = related.R.TriggeredByScanJobs[:ln-1]
		break
	}
	return nil
}

// ScanJobs retrieves all the records using an executor.
func ScanJobs(mods ...qm.QueryMod) scanJobQuery {
	mods = append(mods, qm.From("\"scan_jobs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"scan_jobs\".*"})
	}

	return scanJobQuery{q}
}

// FindScanJob retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindScanJob(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ScanJob, error) {
	scanJobObj := &ScanJob{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"scan_jobs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, scanJobObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from scan_jobs")
	}

	if err = scanJobObj.doAfterSelectHooks(ctx, exec); err != nil {
		return scanJobObj, err
	}

	return scanJobObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ScanJob) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no scan_jobs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scanJobColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	scanJobInsertCacheMut.RLock()
	cache, cached := scanJobInsertCache[key]
	scanJobInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			scanJobAllColumns,
			scanJobColumnsWithDefault,
			scanJobColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(scanJobType, scanJobMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(scanJobType, scanJobMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"scan_jobs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"scan_jobs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into scan_jobs")
	}

	if !cached {
		scanJobInsertCacheMut.Lock()
		scanJobInsertCache[key] = cache
		scanJobInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ScanJob.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ScanJob) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	scanJobUpdateCacheMut.RLock()
	cache, cached := scanJobUpdateCache[key]
	scanJobUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			scanJobAllColumns,
			scanJobPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update scan_jobs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"scan_jobs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, scanJobPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(scanJobType, scanJobMapping, append(wl, scanJobPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update scan_jobs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for scan_jobs")
	}

	if !cached {
		scanJobUpdateCacheMut.Lock()
		scanJobUpdateCache[key] = cache
		scanJobUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q scanJobQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for scan_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for scan_jobs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ScanJobSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scanJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"scan_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, scanJobPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in scanJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all scanJob")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ScanJob) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no scan_jobs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scanJobColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	scanJobUpsertCacheMut.RLock()
	cache, cached := scanJobUpsertCache[key]
	scanJobUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			scanJobAllColumns,
			scanJobColumnsWithDefault,
			scanJobColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			scanJobAllColumns,
			scanJobPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert scan_jobs, could not build update column list")
		}

		ret := strmangle.SetComplement(scanJobAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(scanJobPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert scan_jobs, could not build conflict column list")
			}

			conflict = make([]string, len(scanJobPrimaryKeyColumns))
			copy(conflict, scanJobPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"scan_jobs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(scanJobType, scanJobMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(scanJobType, scanJobMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert scan_jobs")
	}

	if !cached {
		scanJobUpsertCacheMut.Lock()
		scanJobUpsertCache[key] = cache
		scanJobUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ScanJob record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ScanJob) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ScanJob provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), scanJobPrimaryKeyMapping)
	sql := "DELETE FROM \"scan_jobs\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from scan_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for scan_jobs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q scanJobQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no scanJobQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from scan_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for scan_jobs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ScanJobSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(scanJobBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scanJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"scan_jobs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scanJobPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from scanJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for scan_jobs")
	}

	if len(scanJobAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ScanJob) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindScanJob(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ScanJobSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ScanJobSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scanJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"scan_jobs\".* FROM \"scan_jobs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scanJobPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ScanJobSlice")
	}

	*o = slice

	return nil
}

// ScanJobExists checks if the ScanJob row exists.
func ScanJobExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"scan_jobs\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if scan_jobs exists")
	}

	return exists, nil
}

// Exists checks if the ScanJob row exists.
func (o *ScanJob) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ScanJobExists(ctx, exec, o.ID)
}
