// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testScanJobs(t *testing.T) {
	t.Parallel()

	query := ScanJobs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testScanJobsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testScanJobsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ScanJobs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testScanJobsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ScanJobSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testScanJobsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ScanJobExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ScanJob exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ScanJobExists to return true, but got false.")
	}
}

func testScanJobsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	scanJobFound, err := FindScanJob(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if scanJobFound == nil {
		t.Error("want a record, got nil")
	}
}

func testScanJobsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ScanJobs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testScanJobsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ScanJobs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testScanJobsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	scanJobOne := &ScanJob{}
	scanJobTwo := &ScanJob{}
	if err = randomize.Struct(seed, scanJobOne, scanJobDBTypes, false, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}
	if err = randomize.Struct(seed, scanJobTwo, scanJobDBTypes, false, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = scanJobOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = scanJobTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ScanJobs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testScanJobsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	scanJobOne := &ScanJob{}
	scanJobTwo := &ScanJob{}
	if err = randomize.Struct(seed, scanJobOne, scanJobDBTypes, false, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}
	if err = randomize.Struct(seed, scanJobTwo, scanJobDBTypes, false, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = scanJobOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = scanJobTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func scanJobBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func scanJobAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func scanJobAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func scanJobBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func scanJobAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func scanJobBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func scanJobAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func scanJobBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func scanJobAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ScanJob) error {
	*o = ScanJob{}
	return nil
}

func testScanJobsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ScanJob{}
	o := &ScanJob{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, scanJobDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ScanJob object: %s", err)
	}

	AddScanJobHook(boil.BeforeInsertHook, scanJobBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	scanJobBeforeInsertHooks = []ScanJobHook{}

	AddScanJobHook(boil.AfterInsertHook, scanJobAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	scanJobAfterInsertHooks = []ScanJobHook{}

	AddScanJobHook(boil.AfterSelectHook, scanJobAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	scanJobAfterSelectHooks = []ScanJobHook{}

	AddScanJobHook(boil.BeforeUpdateHook, scanJobBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	scanJobBeforeUpdateHooks = []ScanJobHook{}

	AddScanJobHook(boil.AfterUpdateHook, scanJobAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	scanJobAfterUpdateHooks = []ScanJobHook{}

	AddScanJobHook(boil.BeforeDeleteHook, scanJobBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	scanJobBeforeDeleteHooks = []ScanJobHook{}

	AddScanJobHook(boil.AfterDeleteHook, scanJobAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	scanJobAfterDeleteHooks = []ScanJobHook{}

	AddScanJobHook(boil.BeforeUpsertHook, scanJobBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	scanJobBeforeUpsertHooks = []ScanJobHook{}

	AddScanJobHook(boil.AfterUpsertHook, scanJobAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	scanJobAfterUpsertHooks = []ScanJobHook{}
}

func testScanJobsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testScanJobsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testScanJobToOneProjectUsingProject(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ScanJob
	var foreign Project

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, projectDBTypes, false, projectColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Project struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.ProjectID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Project().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddProjectHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Project) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ScanJobSlice{&local}
	if err = local.L.LoadProject(ctx, tx, false, (*[]*ScanJob)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Project == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Project = nil
	if err = local.L.LoadProject(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Project == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testScanJobToOneSbomUsingSbom(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ScanJob
	var foreign Sbom

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, sbomDBTypes, false, sbomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Sbom struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.SbomID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Sbom().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddSbomHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Sbom) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ScanJobSlice{&local}
	if err = local.L.LoadSbom(ctx, tx, false, (*[]*ScanJob)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Sbom == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Sbom = nil
	if err = local.L.LoadSbom(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Sbom == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testScanJobToOneUserUsingTriggeredByUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ScanJob
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.TriggeredBy, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.TriggeredByUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ScanJobSlice{&local}
	if err = local.L.LoadTriggeredByUser(ctx, tx, false, (*[]*ScanJob)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TriggeredByUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.TriggeredByUser = nil
	if err = local.L.LoadTriggeredByUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TriggeredByUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testScanJobToOneSetOpProjectUsingProject(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ScanJob
	var b, c Project

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, projectDBTypes, false, strmangle.SetComplement(projectPrimaryKeyColumns, projectColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, projectDBTypes, false, strmangle.SetComplement(projectPrimaryKeyColumns, projectColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Project{&b, &c} {
		err = a.SetProject(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Project != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ScanJobs[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.ProjectID, x.ID) {
			t.Error("foreign key was wrong value", a.ProjectID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ProjectID))
		reflect.Indirect(reflect.ValueOf(&a.ProjectID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.ProjectID, x.ID) {
			t.Error("foreign key was wrong value", a.ProjectID, x.ID)
		}
	}
}

func testScanJobToOneRemoveOpProjectUsingProject(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ScanJob
	var b Project

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, projectDBTypes, false, strmangle.SetComplement(projectPrimaryKeyColumns, projectColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetProject(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveProject(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Project().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Project != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.ProjectID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.ScanJobs) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testScanJobToOneSetOpSbomUsingSbom(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ScanJob
	var b, c Sbom

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, sbomDBTypes, false, strmangle.SetComplement(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, sbomDBTypes, false, strmangle.SetComplement(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Sbom{&b, &c} {
		err = a.SetSbom(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Sbom != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ScanJobs[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.SbomID, x.ID) {
			t.Error("foreign key was wrong value", a.SbomID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.SbomID))
		reflect.Indirect(reflect.ValueOf(&a.SbomID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.SbomID, x.ID) {
			t.Error("foreign key was wrong value", a.SbomID, x.ID)
		}
	}
}

func testScanJobToOneRemoveOpSbomUsingSbom(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ScanJob
	var b Sbom

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, sbomDBTypes, false, strmangle.SetComplement(sbomPrimaryKeyColumns, sbomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetSbom(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveSbom(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Sbom().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Sbom != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.SbomID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.ScanJobs) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testScanJobToOneSetOpUserUsingTriggeredByUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ScanJob
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetTriggeredByUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.TriggeredByUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TriggeredByScanJobs[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.TriggeredBy, x.ID) {
			t.Error("foreign key was wrong value", a.TriggeredBy)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TriggeredBy))
		reflect.Indirect(reflect.ValueOf(&a.TriggeredBy)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.TriggeredBy, x.ID) {
			t.Error("foreign key was wrong value", a.TriggeredBy, x.ID)
		}
	}
}

func testScanJobToOneRemoveOpUserUsingTriggeredByUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ScanJob
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, scanJobDBTypes, false, strmangle.SetComplement(scanJobPrimaryKeyColumns, scanJobColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetTriggeredByUser(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveTriggeredByUser(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.TriggeredByUser().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.TriggeredByUser != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.TriggeredBy) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.TriggeredByScanJobs) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testScanJobsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testScanJobsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ScanJobSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testScanJobsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ScanJobs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	scanJobDBTypes = map[string]string{`ID`: `bigint`, `ProjectID`: `integer`, `SbomID`: `uuid`, `Status`: `character varying`, `ScanType`: `character varying`, `TriggeredBy`: `integer`, `StartedAt`: `timestamp with time zone`, `FinishedAt`: `timestamp with time zone`, `ErrorLog`: `text`, `Meta`: `jsonb`, `CreatedAt`: `timestamp with time zone`}
	_              = bytes.MinRead
)

func testScanJobsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(scanJobPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(scanJobAllColumns) == len(scanJobPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testScanJobsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(scanJobAllColumns) == len(scanJobPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ScanJob{}
	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, scanJobDBTypes, true, scanJobPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(scanJobAllColumns, scanJobPrimaryKeyColumns) {
		fields = scanJobAllColumns
	} else {
		fields = strmangle.SetComplement(
			scanJobAllColumns,
			scanJobPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ScanJobSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testScanJobsUpsert(t *testing.T) {
	t.Parallel()

	if len(scanJobAllColumns) == len(scanJobPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ScanJob{}
	if err = randomize.Struct(seed, &o, scanJobDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ScanJob: %s", err)
	}

	count, err := ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, scanJobDBTypes, false, scanJobPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ScanJob struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ScanJob: %s", err)
	}

	count, err = ScanJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
